import {
	EntityId,
	EntityRef
} from 'types/cordium';

export enum ApplicationState {
	UNKNOWN = -1,

	NONE = 0,

	OK = 1,

	INVALIDAPIKEY = 2,
	INVALIDPAYLOADARGUMENTS = 3,
	MALFORMEDREQUEST = 4,
	INVALIDUSER = 5,
	INVALIDCREDENTIALS = 6,
	INVALIDLINK = 7,
	EXPIREDLINK = 8,

	UNAUTHORIZEDOPERATION = 9,
	LOCKEDOUT = 10,

	PASSWORDDOESNOTMEETREQUIREMENTS = 11,
	ERRORCREATINGAUTHORIZATION = 12,
	ERRORCREATINGPASSWORD = 13,
	ERRORSAVINGPASSWORD = 14,
	ERRORSAVINGAUTHORIZATION = 15,
	ERRORCREATINGONETIMEPASSWORDDEVICE = 16,
	TWOFACTORDEVICENOTPROVISIONED = 17,
	ERRORCREATINGRECOVERYCODES = 18,
	USERNOTACTIVATED = 19,
	ERRORCREATINGJWT = 20,
	INVALIDJWT = 21,
	INVALIDVISA = 22,
	ERRORSENDINGACTIVATIONEMAIL = 23,
	INVALIDFILETYPE = 24,
	INVALIDTWOFACTORCODE = 25
}

export interface StatusType {
	message: string | null;
	type: ApplicationState;
}
